baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'MeowRain Blog'
theme = "FixIt"
defaultContentLanguage = 'zh-cn'
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "archives"
    parent = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "归档"
    url = "/archives/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
    # FixIt 0.2.14 | NEW add user-defined content to menu items
    [menu.main.params]
      # add css class to a specific menu item
      class = ""
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-archive"
      # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
      type = ""
  [[menu.main]]
    identifier = "categories"
    parent = ""
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
  [[menu.main]]
    identifier = "tags"
    parent = ""
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    identifier = "friends"
    parent = ""
    pre = ""
    post = ""
    name = "友链"
    url = "/friends/"
    title = ""
    weight = 4
    [menu.main.params]
      icon = "fa-solid fa-folder"
  [[menu.main]]
    identifier = "about"
    parent = ""
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = "关于"
    weight = 5
    [menu.main.params]
      icon = "fa-solid fa-user"
# -------------------------------------------------------------------------------------
# Markup related configuration in Hugo
# See: https://gohugo.io/getting-started/configuration-markup/
# -------------------------------------------------------------------------------------

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ########## necessary configurations ##########
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    ########## necessary configurations ##########
    guessSyntax = true
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    ordered = false
    startLevel = 1
    endLevel = 6
# -------------------------------------------------------------------------------------
# Sitemap Configuration
# See: https://gohugo.io/templates/sitemap-template/#configuration
# -------------------------------------------------------------------------------------

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "posts/:slugorfilename"
# -------------------------------------------------------------------------------------
# Privacy Configuration
# See: https://gohugo.io/about/hugo-and-gdpr/
# -------------------------------------------------------------------------------------

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
# -------------------------------------------------------------------------------------
# Media Types
# See: https://gohugo.io/templates/output-formats/#media-types
# -------------------------------------------------------------------------------------

[mediaTypes]
  # Options to make output .md files
  [mediaTypes."text/markdown"]
    suffixes = ["md"]
  # Options to make output .txt files
  [mediaTypes."text/plain"]
    suffixes = ["txt"]
# -------------------------------------------------------------------------------------
# Output Format Definitions
# See: https://gohugo.io/templates/output-formats/#output-format-definitions
# -------------------------------------------------------------------------------------

[outputFormats]
  # Options to make output .md files
  [outputFormats.MarkDown]
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  # FixIt 0.3.0 | NEW Options to make output /archives/index.html file
  [outputFormats.archives]
    path = "archives"
    baseName = "index"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    permalinkable = true
  # FixIt 0.3.0 | NEW Options to make output /offline/index.html file
  [outputFormats.offline]
    path = "offline"
    baseName = "index"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    permalinkable = true
  # FixIt 0.3.0 | NEW Options to make output readme.md file
  [outputFormats.README]
    baseName = "readme"
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  # FixIt 0.3.0 | CHANGED Options to make output baidu_urls.txt file
  [outputFormats.baidu_urls]
    baseName = "baidu_urls"
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

# -------------------------------------------------------------------------------------
# Customizing Output Formats
# See: https://gohugo.io/templates/output-formats/#customizing-output-formats
# -------------------------------------------------------------------------------------

# Options to make hugo output files, the optional values are below:
# home: ["HTML", "RSS", "JSON", "archives", "offline", "README", "baidu_urls"]
# page: ["HTML", "MarkDown"]
# section: ["HTML", "RSS"]
# taxonomy: ["HTML", "RSS"]
# term: ["HTML", "RSS"]
[outputs]
  home = ["HTML", "RSS", "JSON", "archives"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML", "RSS"]


# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[params]
  # FixIt 0.2.15 | CHANGED FixIt theme version
  version = "0.3.X" # e.g. "0.2.X", "0.2.15", "v0.2.15" etc.
  # site description
  description = ""
  # site keywords
  keywords = []
  # site default theme ["light", "dark", "auto"]
  defaultTheme = "auto"
  # which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # NEW date format
  dateFormat = "2006-01-02"
  # website images for Open Graph and Twitter Cards
  images = []
  # FixIt 0.2.12 | NEW enable PWA
  enablePWA = true
  # FixIt 0.2.14 | NEW whether to add external Icon for external links automatically
  externalIcon = false
  # FixIt 0.3.0 | NEW whether to reverse the order of the navigation menu
  navigationReverse = false
  # FixIt 0.3.0 | NEW whether to add site title to the title of every page
  # remember to set up your site title in `hugo.toml` (e.g. title = "title")
  withSiteTitle = true
  # FixIt 0.3.0 | NEW title delimiter when the site title is be added to the title of every page
  titleDelimiter = "-"
  # FixIt 0.3.0 | NEW whether to add site subtitle to the title of index page
  # remember to set up your site subtitle by `params.header.subtitle.name`
  indexWithSubtitle = false
  # FixIt 0.2.14 | NEW FixIt will, by default, inject a theme meta tag in the HTML head on the home page only.
  # You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch FixIt's popularity on the rise.
  disableThemeInject = false

  # Author Configuration
  [params.author]
    name = "meowrain"
    email = "meowrain@126.com"


  # FixIt 0.3.0 | NEW public Git repository information only then enableGitInfo is true
  [params.gitInfo]
    # e.g. "https://github.com/hugo-fixit/docs"
    repo = "https://github.com/meowrain/hugo-blog"
    branch = "main"
    # the content directory path relative to the root of the repository
    dir = "content"
    # the issue template for reporting issue of the posts
    # available template params: {title} {URL} {sourceURL}
    issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"

  # App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "MeowRain's Blog"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
    # FixIt 0.2.12 | CHANGED Android browser theme color
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"

  # Search config
  [params.search]
    enable = true
    # type of search engine ["algolia", "fuse"]
    type = "fuse"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      # FixIt 0.2.17 | NEW https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false

  # Header config
  [params.header]
    # FixIt 0.2.13 | CHANGED desktop header mode ["sticky", "normal", "auto"]
    desktopMode = "sticky"
    # FixIt 0.2.13 | CHANGED mobile header mode ["sticky", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "MeowRain's Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = "✨"
      # you can add extra information after the name (HTML format is supported), such as icons
      post = "✨"
      # whether to use typeit animation for title name
      typeit = false
    # FixIt 0.2.12 | NEW Header subtitle config
    [params.header.subtitle]
      # subtitle name
      name = ""
      # whether to use typeit animation for subtitle name
      typeit = false

  # FixIt 0.2.18 | NEW Breadcrumb config
  [params.breadcrumb]
    enable = true
    sticky = true
    showHome = true

  # Footer config
  [params.footer]
    enable = true
    # FixIt 0.2.17 | CHANGED Custom content (HTML format is supported)
    # For advanced use, see parameter `params.customFilePath.footer`
    custom = ""
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # Site creation year
    since = "2020"
    # FixIt 0.2.12 | NEW Public network security only in China (HTML format is supported)
    gov = ""
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = ""
    # FixIt 0.3.0 | NEW whether to show Hugo and theme info
    [params.footer.powered]
      enable = true
      hugoLogo = true
      themeLogo = true
    # FixIt 0.2.17 | CHANGED Site creation time
    [params.footer.siteTime]
      enable = false
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "" # e.g. "2021-12-18T16:15:22+08:00"
    # FixIt 0.2.17 | NEW footer lines order, optional values: ["first", 0, 1, 2, 3, 4, 5, "last"]
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0

  # FixIt 0.3.0 | NEW Archives page config (all pages of posts type)
  [params.archives]
    # special amount of posts in archives page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"

  # Section page config (all pages in section)
  [params.section]
    # special amount of pages in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
    # FixIt 0.2.13 | NEW recently updated pages config
    # TODO refactor to support archives, section, taxonomy and term
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10

  # List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # FixIt 0.2.17 | NEW TagCloud config for tags page
  [params.tagcloud]
    enable = false
    min = 14 # Minimum font size in px
    max = 32 # Maximum font size in px
    peakCount = 10 # Maximum count of posts per tag
    orderby = "name" # Order of tags, optional values: ["name", "count"]

  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "meowrain@126.com"
      # URL of avatar shown in home page
      avatarURL = "https://avatars.githubusercontent.com/u/107172084?v=4"
      # FixIt 0.2.17 | NEW identifier of avatar menu link
      avatarMenu = ""
      # title shown in home page (HTML format is supported)
      title = "MeowRain"
      # subtitle shown in home page
      subtitle = "Life is Simple"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 10
      # FixIt 0.2.16 | CHANGED Social config about the author
  [params.social]
    GitHub = "https://github.com/meowrain"
  # FixIt 0.2.15 | NEW Mermaid config
  [params.mermaid]
    # For values, see https://mermaid.js.org/config/theming.html#available-themes
    themes = ["default", "dark"]
  # FixIt 0.2.12 | NEW PanguJS config
  [params.pangu]
    # For Chinese writing
    enable = true
    selector = "article" # FixIt 0.2.17 | NEW
# FixIt 0.2.12 | NEW Watermark config
  # Detail config see https://github.com/Lruihao/watermark#readme
  [params.watermark]
    enable = false
    # watermark's text (HTML format is supported)
    content = ""
    # watermark's transparency
    opacity = 0.1
    # watermark's width. unit: px
    width = 150
    # watermark's height. unit: px
    height = 20
    # row spacing of watermarks. unit: px
    rowSpacing = 60
    # col spacing of watermarks. unit: px
    colSpacing = 30
    # watermark's tangent angle. unit: deg
    rotate = 15
    # watermark's fontSize. unit: rem
    fontSize = 0.85
    # FixIt 0.2.13 | NEW watermark's fontFamily
    fontFamily = "inherit"
  # Cookie consent config
  [params.cookieconsent]
    enable = false
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""
  # FixIt 0.2.14 | NEW GitHub banner in the top-right or top-left corner
  [params.githubCorner]
    enable = true
    permalink = "https://github.com/meowrain/hugo-blog"
    title = "View source on GitHub"
    position = "right" # ["left", "right"]
 # FixIt 0.2.14 | NEW Gravatar config
  [params.gravatar]
    # FixIt 0.2.18 | NEW Depends on the author's email, if the author's email is not set, the local avatar will be used
    enable = false
    # Gravatar host, default: "www.gravatar.com"
    host = "www.gravatar.com" # ["cravatar.cn", "gravatar.loli.net", ...]
    style = "" # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]
      # FixIt 0.2.16 | NEW Back to top
  [params.backToTop]
    enable = true
    # Scroll percent label in b2t button
    scrollpercent = true
 # FixIt 0.2.16 | NEW Reading progress bar
  [params.readingProgress]
    enable = true
    # Available values: ["left", "right"]
    start = "left"
    # Available values: ["top", "bottom"]
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"
 [params.pace]
    enable = false
    # All available colors:
    # ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
    color = "blue"
    # All available themes:
    # ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
    # "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
    theme = "minimal"
   # Page config
  [params.page]
    # FixIt 0.2.18 | NEW whether to enable the author's avatar of the post
    authorAvatar = true
    pageStyle = "normal"
    # FixIt 0.2.17 | NEW whether to enable wordCount
    wordCount = true
        # FixIt 0.2.17 | NEW whether to enable readingTime
    readingTime = true
    # Table of the contents config

    # Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = false
      # FixIt 0.2.13 | NEW position of TOC ["left", "right"]
      position = "right"
    # FixIt 0.2.13 | NEW Display a message at the beginning of an article to warn the reader that its content might be expired
    [params.page.expirationReminder]
      enable = true
      # Display the reminder if the last modified time is more than 90 days ago
      reminder = 90
      # Display warning if the last modified time is more than 180 days ago
      warning = 180
      # If the article expires, close the comment or not
      closeComment = false
    [params.page.math]
      enable = true
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
    [params.page.related]
      enable = true
      count = 5

